# Generated by Django 3.1 on 2022-03-17 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='location',
            field=models.CharField(choices=[('home', 'Գլխավոր էջ'), ('how_to_order', 'Ինչպես պատվիրել'), ('product_page', 'Ապրանքի էջ')], default='home', max_length=100, verbose_name='Ընտրեք էջը'),
        ),
    ]
