# Generated by Django 3.1 on 2022-04-02 08:36

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
