# Generated by Django 3.1 on 2022-04-02 08:37

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_video_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Տեքստ'),
        ),
    ]
