# Generated by Django 3.1 on 2022-05-15 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_auto_20220402_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='location',
            field=models.CharField(choices=[('home', 'Գլխավոր էջ'), ('how_to_order', 'Ինչպես պատվիրել'), ('product_page', 'Ապրանքի էջ'), ('job', 'Թափուր հաստիքներ')], default='home', max_length=100, verbose_name='Ընտրեք էջը'),
        ),
    ]
