# Generated by Django 3.1 on 2023-02-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_auto_20230222_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='location',
            field=models.CharField(choices=[('home', 'Գլխավոր էջ')], default='home', max_length=100, verbose_name='Ընտրեք էջը'),
        ),
    ]
