# Generated by Django 3.1 on 2022-03-07 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220226_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=123456789, max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
