# Generated by Django 3.1 on 2022-03-07 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blocked_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
