# Generated by Django 3.1 on 2022-03-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
