# Generated by Django 3.1 on 2022-03-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sent_verification_code',
            field=models.BooleanField(default=False),
        ),
    ]
