# Generated by Django 3.1 on 2022-03-08 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_sent_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
