# Generated by Django 3.1 on 2022-03-10 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20220310_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('personal', 'Ֆիզիկական'), ('company', 'Իրավաբանական')], default=1, max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='blocked_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=223332, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='sent_verification_code',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
