# Generated by Django 3.1 on 2022-03-12 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20220311_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='fact_city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='fact_state',
        ),
        migrations.RemoveField(
            model_name='user',
            name='register_city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='register_state',
        ),
        migrations.RemoveField(
            model_name='user',
            name='state',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
