# Generated by Django 3.1 on 2022-03-12 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20220312_0822'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Մարզ',
                'verbose_name_plural': 'Մարզեր',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField(default=0)),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.state')),
            ],
            options={
                'verbose_name': 'Քաղաք/գյուղ',
                'verbose_name_plural': 'Քաղաքներ,գյուղեր',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usercity', to='users.country'),
        ),
        migrations.AddField(
            model_name='user',
            name='fact_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factcity', to='users.country', verbose_name='Ընկերության փաստացի հասցե(քաղաք)'),
        ),
        migrations.AddField(
            model_name='user',
            name='fact_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factstate', to='users.state', verbose_name='Ընկերության փաստացի հասցե(մարզ)'),
        ),
        migrations.AddField(
            model_name='user',
            name='register_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regcity', to='users.country', verbose_name='Ընկերության գրանցման հասցե(քաղաք)'),
        ),
        migrations.AddField(
            model_name='user',
            name='register_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regstate', to='users.state', verbose_name='Ընկերության գրանցման հասցե(մարզ)'),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userstate', to='users.state'),
        ),
    ]
