# Generated by Django 3.1 on 2022-03-12 10:21

import canapea.utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20220312_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=canapea.utils.CustomLogoField(blank=True, null=True, upload_to=''),
        ),
    ]
