# Generated by Django 3.1 on 2022-03-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='attempts_count',
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
