# Generated by Django 3.1 on 2022-03-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_user_attempts_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='attempts_count',
            field=models.PositiveSmallIntegerField(default=4),
        ),
    ]
