# Generated by Django 3.1 on 2023-02-23 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20220314_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='state',
            name='name_hy',
        ),
        migrations.RemoveField(
            model_name='state',
            name='name_ru',
        ),
    ]
