# Generated by Django 3.1 on 2023-02-25 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20230223_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='attempts_count',
        ),
        migrations.RemoveField(
            model_name='user',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='company_spher',
        ),
        migrations.RemoveField(
            model_name='user',
            name='company_website',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='fact_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='fact_city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='fact_state',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='register_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='register_city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='register_state',
        ),
        migrations.RemoveField(
            model_name='user',
            name='res_position',
        ),
        migrations.RemoveField(
            model_name='user',
            name='resfirst_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='reslast_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tin',
        ),
    ]
