# Generated by Django 3.1 on 2023-03-04 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20230225_1442'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Country',
            new_name='Region',
        ),
    ]
