# Generated by Django 3.1 on 2023-03-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20230305_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bonuses_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
