# Generated by Django 3.1 on 2022-04-01 09:14

import canapea.utils
import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ստեղծման օր')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ձևափոխման օր')),
                ('file', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['flv', 'mp4'])], verbose_name='Մեր մասին -ի նկար կամ հոլովակ')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Հոլովակի հղում')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GoalImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', canapea.utils.CustomLogoField(upload_to='')),
            ],
            options={
                'verbose_name_plural': '«Մեր նպատակները» հատվածի նկար',
            },
        ),
        migrations.CreateModel(
            name='OurAdvantages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ստեղծման օր')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ձևափոխման օր')),
                ('my_order', models.PositiveIntegerField(default=0, verbose_name='Դասավորել')),
                ('icon', canapea.utils.CustomLogoField(upload_to='')),
                ('name', models.CharField(max_length=255, verbose_name='Նպատակի անուն')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Նկարագրություն')),
            ],
            options={
                'verbose_name': 'Առավելություն',
                'verbose_name_plural': 'Մեր առավելությունները',
                'ordering': ['-my_order'],
            },
        ),
        migrations.CreateModel(
            name='OurGoals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ստեղծման օր')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ձևափոխման օր')),
                ('my_order', models.PositiveIntegerField(default=0, verbose_name='Դասավորել')),
                ('name', models.CharField(max_length=255, verbose_name='Նպատակի անուն')),
                ('name_hy', models.CharField(max_length=255, null=True, verbose_name='Նպատակի անուն')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Նպատակի անուն')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Նպատակի անուն')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Նկարագրություն')),
                ('text_hy', models.TextField(blank=True, null=True, verbose_name='Նկարագրություն')),
                ('text_ru', models.TextField(blank=True, null=True, verbose_name='Նկարագրություն')),
                ('text_en', models.TextField(blank=True, null=True, verbose_name='Նկարագրություն')),
            ],
            options={
                'verbose_name': 'Նպատակ',
                'verbose_name_plural': 'Մեր նպատակները',
                'ordering': ['-my_order'],
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ստեղծման օր')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ձևափոխման օր')),
                ('image', canapea.utils.CustomLogoField(upload_to='')),
                ('name', models.CharField(max_length=230, verbose_name='Անուն և ազգանուն')),
                ('text', models.TextField(verbose_name='Կարծիք')),
            ],
            options={
                'verbose_name': 'Կարծիք',
                'verbose_name_plural': '«Մեր մասին» էջի կարծիքներ',
            },
        ),
    ]
