# Generated by Django 3.1 on 2022-04-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0002_auto_20220401_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='name_en',
            field=models.CharField(max_length=230, null=True, verbose_name='Անուն և ազգանուն'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='name_hy',
            field=models.CharField(max_length=230, null=True, verbose_name='Անուն և ազգանուն'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='name_ru',
            field=models.CharField(max_length=230, null=True, verbose_name='Անուն և ազգանուն'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='text_en',
            field=models.TextField(null=True, verbose_name='Կարծիք'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='text_hy',
            field=models.TextField(null=True, verbose_name='Կարծիք'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Կարծիք'),
        ),
    ]
