# Generated by Django 3.1 on 2022-04-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0004_auto_20220401_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='ouradvantages',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Նպատակի անուն'),
        ),
        migrations.AddField(
            model_name='ouradvantages',
            name='name_hy',
            field=models.CharField(max_length=255, null=True, verbose_name='Նպատակի անուն'),
        ),
        migrations.AddField(
            model_name='ouradvantages',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Նպատակի անուն'),
        ),
        migrations.AddField(
            model_name='ouradvantages',
            name='text_en',
            field=models.TextField(blank=True, null=True, verbose_name='Նկարագրություն'),
        ),
        migrations.AddField(
            model_name='ouradvantages',
            name='text_hy',
            field=models.TextField(blank=True, null=True, verbose_name='Նկարագրություն'),
        ),
        migrations.AddField(
            model_name='ouradvantages',
            name='text_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Նկարագրություն'),
        ),
    ]
