# Generated by Django 3.1 on 2022-04-01 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0005_auto_20220401_0946'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name_plural': 'Մեր մասին'},
        ),
    ]
