# Generated by Django 3.1 on 2022-04-01 09:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0006_auto_20220401_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='file',
            field=models.FileField(blank=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['flv', 'mp4', 'svg', 'jpg', 'png'])], verbose_name='Մեր մասին -ի նկար կամ հոլովակ'),
        ),
    ]
