# Generated by Django 3.1 on 2023-02-22 19:20

import beercity.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0007_auto_20220401_0950'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Անուն (alt)')),
                ('name_hy', models.CharField(blank=True, max_length=200, null=True, verbose_name='Անուն (alt)')),
                ('name_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Անուն (alt)')),
                ('name_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Անուն (alt)')),
                ('icon', beercity.utils.CustomLogoField(upload_to='')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Հղում դեպի գործընկերոջ կայքէջ')),
                ('url_hy', models.URLField(blank=True, null=True, verbose_name='Հղում դեպի գործընկերոջ կայքէջ')),
                ('url_ru', models.URLField(blank=True, null=True, verbose_name='Հղում դեպի գործընկերոջ կայքէջ')),
                ('url_en', models.URLField(blank=True, null=True, verbose_name='Հղում դեպի գործընկերոջ կայքէջ')),
                ('my_order', models.PositiveIntegerField(default=0, verbose_name='Դասավորել')),
            ],
            options={
                'verbose_name': 'Գործընկեր',
                'verbose_name_plural': 'Գործընկերներ',
                'ordering': ['my_order'],
            },
        ),
    ]
