# Generated by Django 3.1 on 2023-02-27 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0008_partners'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OurAdvantages',
        ),
    ]
