# Generated by Django 3.2.7 on 2022-11-05 14:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0010_auto_20220920_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactuspage',
            name='contact_bg_image',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'svg', 'png', 'jpeg', 'webp'])], verbose_name='Background -ի Նկար'),
        ),
    ]
