# Generated by Django 3.2.7 on 2023-01-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0012_followuscontactus_phone_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followuscontactus',
            name='phone_url',
        ),
        migrations.AddField(
            model_name='contactusjoinusdata',
            name='phone_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Mobile -ի Հղում'),
        ),
    ]
