# Generated by Django 3.1 on 2023-02-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0014_auto_20230224_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactusjoinusdata',
            name='text_en',
            field=models.CharField(max_length=400, null=True, verbose_name='Տեքստ'),
        ),
        migrations.AddField(
            model_name='contactusjoinusdata',
            name='text_hy',
            field=models.CharField(max_length=400, null=True, verbose_name='Տեքստ'),
        ),
        migrations.AddField(
            model_name='contactusjoinusdata',
            name='text_ru',
            field=models.CharField(max_length=400, null=True, verbose_name='Տեքստ'),
        ),
    ]
