# Generated by Django 3.1 on 2023-02-27 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0015_auto_20230224_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
