# Generated by Django 3.1 on 2022-02-21 19:53

import beercity.utils
import ckeditor_uploader.fields
import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=160)),
                ('meta_description', models.TextField(blank=True, max_length=300)),
                ('name', models.CharField(max_length=255, verbose_name='Բաժնի անուն')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Հղում')),
                ('homepage_name', models.CharField(blank=True, max_length=255, verbose_name='Գլխավոր էջում երևացող անուն')),
                ('icon', beercity.utils.CustomLogoField(upload_to='', verbose_name='Նկար')),
                ('logo', beercity.utils.CustomLogoField(upload_to='', verbose_name='Icon')),
                ('short_description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Հակիրճ նկարագիր')),
                ('large_description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Ամբողջական նկարագիր')),
                ('notification_text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Notification -ի տեքստ')),
                ('working_hours_from', models.TimeField(blank=True, null=True, verbose_name='Աշխատաժամի սկիզբ')),
                ('working_hours_to', models.TimeField(blank=True, null=True, verbose_name='Աշխատաժամի ավարտ')),
                ('color', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None, verbose_name='Գույն')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='shop.category', verbose_name='Հայրական բաժին')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
