# Generated by Django 3.1 on 2022-02-21 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Բաժին', 'verbose_name_plural': 'Բաժիններ'},
        ),
    ]
