# Generated by Django 3.1 on 2022-02-21 20:14

import canapea.utils
import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20220221_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', help_text='Այս դաշտի արդյունքը երևում է գլխավոր էջի վերևի բաժիններ֊ի հատվածում', image_field=None, max_length=18, samples=None, verbose_name='Background -ի գույն'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=canapea.utils.CustomLogoField(blank=True, null=True, upload_to='', verbose_name='Նկար'),
        ),
        migrations.AlterField(
            model_name='category',
            name='logo',
            field=canapea.utils.CustomLogoField(blank=True, null=True, upload_to='', verbose_name='Icon'),
        ),
    ]
