# Generated by Django 3.1 on 2022-02-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20220221_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='show_on_homepage',
        ),
        migrations.AddField(
            model_name='category',
            name='homepage_qty',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Գլխավոր էջում ցուցադրվող քանակ'),
        ),
        migrations.AddField(
            model_name='category',
            name='show_homepage',
            field=models.BooleanField(default=False, verbose_name='Ցուցադրել գլխավոր էջում որպես տեսականի'),
        ),
        migrations.AddField(
            model_name='category',
            name='show_in_header',
            field=models.BooleanField(default=False, verbose_name='Ցուցադրել header - ի սլայդերում'),
        ),
        migrations.AlterField(
            model_name='category',
            name='notification_text',
            field=models.TextField(blank=True, null=True, verbose_name='Notification -ի տեքստ'),
        ),
        migrations.AlterField(
            model_name='category',
            name='short_description',
            field=models.TextField(blank=True, null=True, verbose_name='Հակիրճ նկարագիր'),
        ),
    ]
