# Generated by Django 3.1 on 2022-02-21 21:06

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20220221_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sub_title_color',
            field=colorfield.fields.ColorField(blank=True, default='#FF0000', help_text='Տարածվող բաժնի բլոկի subcategory -ի անվան ֆոնի գույն', image_field=None, max_length=18, null=True, samples=None, verbose_name='Background -ի գույն'),
        ),
        migrations.AlterField(
            model_name='category',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='#FF0000', help_text='Այս դաշտի արդյունքը երևում է գլխավոր էջի վերևի բաժիններ ֊ի հատվածում', image_field=None, max_length=18, null=True, samples=None, verbose_name='Background -ի գույն'),
        ),
        migrations.AlterField(
            model_name='category',
            name='homepage_name',
            field=models.CharField(blank=True, help_text='Եթե բաժնի անունը երկար է, ապա կարող ենք header -ում օգտագործելավելի կարճ անուն', max_length=255, verbose_name='Header -ում երևացող անուն'),
        ),
        migrations.AlterField(
            model_name='category',
            name='homepage_qty',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Գլխավոր էջում ցուցադրվող subcategory -ների քանակ'),
        ),
        migrations.AlterField(
            model_name='category',
            name='show_homepage',
            field=models.BooleanField(default=False, verbose_name='Ցուցադրել գլխավոր էջում որպես տարածվող բաժին'),
        ),
    ]
