# Generated by Django 4.0.2 on 2022-02-22 19:39

import beercity.utils
import ckeditor_uploader.fields
import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20220221_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='show_bottom',
            field=models.ManyToManyField(blank=True, to='shop.Category', verbose_name='Ցուցադրել ներքևում'),
        ),
        migrations.AlterField(
            model_name='category',
            name='breadcrumb_image',
            field=beercity.utils.CustomLogoField(blank=True, null=True, upload_to='', verbose_name='Բաժնի բանների նկար'),
        ),
        migrations.AlterField(
            model_name='category',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='#FF0000', help_text='Ընտրված գույնը երևում է header -ում, որպես տվյալ բաժնի ֆոնի գույն', image_field=None, max_length=18, null=True, samples=None, verbose_name='Background -ի գույն'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=beercity.utils.CustomLogoField(blank=True, null=True, upload_to='', verbose_name='Ընդհանուր կատալոգում երևացող նկար'),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='category',
            name='large_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Ամբողջական նկարագրություն'),
        ),
        migrations.AlterField(
            model_name='category',
            name='logo',
            field=beercity.utils.CustomLogoField(blank=True, null=True, upload_to='', verbose_name='Header -ի բաժնի Icon'),
        ),
        migrations.AlterField(
            model_name='category',
            name='short_description',
            field=models.TextField(blank=True, null=True, verbose_name='Հակիրճ նկարագրություն'),
        ),
        migrations.AlterField(
            model_name='category',
            name='sub_title_color',
            field=colorfield.fields.ColorField(blank=True, default='#FF0000', help_text='Տարածվում է տվյալ բաժնի բոլոր subcategory -ների անվանումների ֆոնի վրա', image_field=None, max_length=18, null=True, samples=None, verbose_name='subcategory -ի անվան ֆոնի գույն'),
        ),
        migrations.AlterField(
            model_name='category',
            name='working_hours_from',
            field=models.TimeField(blank=True, null=True, verbose_name='Առաքման ժամի սկիզբ'),
        ),
        migrations.AlterField(
            model_name='category',
            name='working_hours_to',
            field=models.TimeField(blank=True, null=True, verbose_name='Առաքման ժամի ավարտ'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
