# Generated by Django 4.0.2 on 2022-02-24 19:30

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_filtervalue_category_add_to_ingredients_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Գույնի անուն')),
                ('color_code', colorfield.fields.ColorField(blank=True, default='#fff', image_field=None, max_length=18, null=True, samples=None, verbose_name='Գույնի կոդ')),
            ],
            options={
                'verbose_name': 'Գույն',
                'verbose_name_plural': 'Գույներ',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
    ]
