# Generated by Django 4.0.2 on 2022-02-24 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_color_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='finally_price',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name=''),
        ),
    ]
