# Generated by Django 4.0.2 on 2022-02-25 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_bonusdays_product_bonus_day_not_working_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Առկա է'),
        ),
    ]
