# Generated by Django 3.1 on 2022-02-26 20:37

import canapea.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_remove_productingredient_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ապրանքի անվանում')),
                ('price', models.IntegerField(default=0, verbose_name='Ապրանքի գին')),
                ('is_active', models.BooleanField(default=True, verbose_name='Առկա է')),
                ('main_image', canapea.utils.CustomLogoField(upload_to='')),
                ('product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
        migrations.AlterField(
            model_name='productingredient',
            name='ingredients',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_ingredients', to='shop.ingredient'),
        ),
    ]
