# Generated by Django 3.1 on 2022-02-26 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_auto_20220226_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='productingredient',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='shop.product'),
            preserve_default=False,
        ),
    ]
