# Generated by Django 3.1 on 2022-02-26 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_auto_20220226_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfeature',
            name='show_on_product_block',
            field=models.BooleanField(default=False, verbose_name='Ցուցադրել ապրանքի բլոկում'),
        ),
    ]
