# Generated by Django 3.1 on 2022-02-27 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_auto_20220226_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='special_offer',
            field=models.BooleanField(default=False, verbose_name='Հատուկ առաջարկ'),
        ),
        migrations.AlterField(
            model_name='productfeature',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Ապրանքի անուն'),
        ),
    ]
