# Generated by Django 3.1 on 2022-02-28 18:41

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_rating_ratingproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonusdays',
            options={'verbose_name': 'Բոնուսային օր', 'verbose_name_plural': 'Բոնուսային օրեր'},
        ),
        migrations.AlterModelOptions(
            name='categorybonuses',
            options={'verbose_name': 'Բաժնի բոնուսային օր', 'verbose_name_plural': 'Բաժնի բոնուսային օրեր'},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'Ինգրեդիոնտ', 'verbose_name_plural': 'Ինգրեդիոնտներ'},
        ),
        migrations.AlterModelOptions(
            name='productingredient',
            options={'ordering': ['my_order'], 'verbose_name': 'Ապրանքի Ինգրեդիենտ', 'verbose_name_plural': 'Ապրանքի Ինգրեդիենտներ'},
        ),
        migrations.AddField(
            model_name='bonusdays',
            name='title_en',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Անուն'),
        ),
        migrations.AddField(
            model_name='bonusdays',
            name='title_hy',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Անուն'),
        ),
        migrations.AddField(
            model_name='bonusdays',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Անուն'),
        ),
        migrations.AddField(
            model_name='category',
            name='homepage_name_en',
            field=models.CharField(blank=True, help_text='Եթե բաժնի անունը երկար է, ապա կարող ենք header -ում օգտագործելավելի կարճ անուն', max_length=255, null=True, verbose_name='Header -ում երևացող անուն'),
        ),
        migrations.AddField(
            model_name='category',
            name='homepage_name_hy',
            field=models.CharField(blank=True, help_text='Եթե բաժնի անունը երկար է, ապա կարող ենք header -ում օգտագործելավելի կարճ անուն', max_length=255, null=True, verbose_name='Header -ում երևացող անուն'),
        ),
        migrations.AddField(
            model_name='category',
            name='homepage_name_ru',
            field=models.CharField(blank=True, help_text='Եթե բաժնի անունը երկար է, ապա կարող ենք header -ում օգտագործելավելի կարճ անուն', max_length=255, null=True, verbose_name='Header -ում երևացող անուն'),
        ),
        migrations.AddField(
            model_name='category',
            name='large_description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Ամբողջական նկարագրություն'),
        ),
        migrations.AddField(
            model_name='category',
            name='large_description_hy',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Ամբողջական նկարագրություն'),
        ),
        migrations.AddField(
            model_name='category',
            name='large_description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Ամբողջական նկարագրություն'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Բաժնի անուն'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_hy',
            field=models.CharField(max_length=255, null=True, verbose_name='Բաժնի անուն'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Բաժնի անուն'),
        ),
        migrations.AddField(
            model_name='category',
            name='notification_text_en',
            field=models.TextField(blank=True, null=True, verbose_name='Notification -ի տեքստ'),
        ),
        migrations.AddField(
            model_name='category',
            name='notification_text_hy',
            field=models.TextField(blank=True, null=True, verbose_name='Notification -ի տեքստ'),
        ),
        migrations.AddField(
            model_name='category',
            name='notification_text_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Notification -ի տեքստ'),
        ),
        migrations.AddField(
            model_name='category',
            name='short_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Հակիրճ նկարագրություն'),
        ),
        migrations.AddField(
            model_name='category',
            name='short_description_hy',
            field=models.TextField(blank=True, null=True, verbose_name='Հակիրճ նկարագրություն'),
        ),
        migrations.AddField(
            model_name='category',
            name='short_description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Հակիրճ նկարագրություն'),
        ),
        migrations.AddField(
            model_name='color',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Գույնի անուն'),
        ),
        migrations.AddField(
            model_name='color',
            name='title_hy',
            field=models.CharField(max_length=255, null=True, verbose_name='Գույնի անուն'),
        ),
        migrations.AddField(
            model_name='color',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Գույնի անուն'),
        ),
        migrations.AddField(
            model_name='filterfield',
            name='field_type_en',
            field=models.TextField(blank=True, choices=[('radio', 'Radio'), ('select', 'Dropdown')], max_length=50, null=True, verbose_name='Դաշտի տիպը'),
        ),
        migrations.AddField(
            model_name='filterfield',
            name='field_type_hy',
            field=models.TextField(blank=True, choices=[('radio', 'Radio'), ('select', 'Dropdown')], max_length=50, null=True, verbose_name='Դաշտի տիպը'),
        ),
        migrations.AddField(
            model_name='filterfield',
            name='field_type_ru',
            field=models.TextField(blank=True, choices=[('radio', 'Radio'), ('select', 'Dropdown')], max_length=50, null=True, verbose_name='Դաշտի տիպը'),
        ),
        migrations.AddField(
            model_name='filterfield',
            name='help_field_content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Օգնող դաշտի տեքստ'),
        ),
        migrations.AddField(
            model_name='filterfield',
            name='help_field_content_hy',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Օգնող դաշտի տեքստ'),
        ),
        migrations.AddField(
            model_name='filterfield',
            name='help_field_content_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Օգնող դաշտի տեքստ'),
        ),
        migrations.AddField(
            model_name='filterfield',
            name='help_field_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Օգնող դաշտի վերնագիր'),
        ),
        migrations.AddField(
            model_name='filterfield',
            name='help_field_title_hy',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Օգնող դաշտի վերնագիր'),
        ),
        migrations.AddField(
            model_name='filterfield',
            name='help_field_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Օգնող դաշտի վերնագիր'),
        ),
        migrations.AddField(
            model_name='filterfield',
            name='title_en',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Դաշտի անուն'),
        ),
        migrations.AddField(
            model_name='filterfield',
            name='title_hy',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Դաշտի անուն'),
        ),
        migrations.AddField(
            model_name='filterfield',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Դաշտի անուն'),
        ),
        migrations.AddField(
            model_name='filtervalue',
            name='title_en',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Ֆիլտրացման արժեք'),
        ),
        migrations.AddField(
            model_name='filtervalue',
            name='title_hy',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Ֆիլտրացման արժեք'),
        ),
        migrations.AddField(
            model_name='filtervalue',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Ֆիլտրացման արժեք'),
        ),
        migrations.AddField(
            model_name='product',
            name='large_description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Ամբողջական նկարագրություն'),
        ),
        migrations.AddField(
            model_name='product',
            name='large_description_hy',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Ամբողջական նկարագրություն'),
        ),
        migrations.AddField(
            model_name='product',
            name='large_description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Ամբողջական նկարագրություն'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Ապրանքի անվանում'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_hy',
            field=models.CharField(max_length=255, null=True, verbose_name='Ապրանքի անվանում'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Ապրանքի անվանում'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Հակիրճ նկարագրություն'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_hy',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Հակիրճ նկարագրություն'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Հակիրճ նկարագրություն'),
        ),
        migrations.AddField(
            model_name='productingredient',
            name='my_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Դասավորել'),
        ),
        migrations.AddField(
            model_name='slider',
            name='text_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='text_hy',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='text_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='url_en',
            field=models.URLField(blank=True, null=True, verbose_name='Հղում'),
        ),
        migrations.AddField(
            model_name='slider',
            name='url_hy',
            field=models.URLField(blank=True, null=True, verbose_name='Հղում'),
        ),
        migrations.AddField(
            model_name='slider',
            name='url_ru',
            field=models.URLField(blank=True, null=True, verbose_name='Հղում'),
        ),
        migrations.AlterUniqueTogether(
            name='productingredient',
            unique_together={('product', 'ingredients')},
        ),
    ]
