# Generated by Django 3.1 on 2022-03-01 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_auto_20220228_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sold_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='best_seller',
            field=models.BooleanField(default=False, verbose_name='Թեժ առաջարկ'),
        ),
    ]
