# Generated by Django 3.1 on 2022-03-01 08:16

import canapea.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_auto_20220301_0754'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageBanners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', canapea.utils.CustomLogoField(upload_to='')),
                ('url', models.URLField(verbose_name='Հղում')),
                ('url_hy', models.URLField(null=True, verbose_name='Հղում')),
                ('url_ru', models.URLField(null=True, verbose_name='Հղում')),
                ('url_en', models.URLField(null=True, verbose_name='Հղում')),
                ('name', models.CharField(max_length=255, verbose_name='Վերնագիր')),
                ('name_hy', models.CharField(max_length=255, null=True, verbose_name='Վերնագիր')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Վերնագիր')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Վերնագիր')),
                ('my_order', models.PositiveIntegerField(default=0, verbose_name='Դասավորել')),
            ],
            options={
                'verbose_name': 'Գլխավոր էջի բաններ',
                'verbose_name_plural': 'Գլխավոր էջի բաններներ',
                'ordering': ['my_order'],
            },
        ),
    ]
