# Generated by Django 3.1 on 2022-03-01 08:37

import beercity.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_homepagebanners'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bullets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Վերնագիր')),
                ('title_hy', models.CharField(max_length=255, null=True, verbose_name='Վերնագիր')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Վերնագիր')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Վերնագիր')),
                ('icon', beercity.utils.CustomLogoField(upload_to='')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Նկարագիր')),
                ('text_hy', models.TextField(blank=True, null=True, verbose_name='Նկարագիր')),
                ('text_ru', models.TextField(blank=True, null=True, verbose_name='Նկարագիր')),
                ('text_en', models.TextField(blank=True, null=True, verbose_name='Նկարագիր')),
                ('my_order', models.PositiveIntegerField(default=0, verbose_name='Դասավորել')),
            ],
            options={
                'verbose_name': 'Գլխավոր էջի բաններ',
                'verbose_name_plural': 'Գլխավոր էջի բաններներ',
                'ordering': ['my_order'],
            },
        ),
    ]
