# Generated by Django 3.1 on 2022-03-01 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_bullets'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bullets',
            options={'ordering': ['my_order'], 'verbose_name': 'Առավելություն', 'verbose_name_plural': 'Մեր առավելություններ'},
        ),
    ]
