# Generated by Django 3.1 on 2022-03-02 18:50

import beercity.utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_subscriptions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptions',
            options={'verbose_name': 'Բաժանորդագրություն', 'verbose_name_plural': 'Բաժանորդագրություններ'},
        ),
        migrations.RemoveField(
            model_name='filterfield',
            name='field_type_en',
        ),
        migrations.RemoveField(
            model_name='filterfield',
            name='field_type_hy',
        ),
        migrations.RemoveField(
            model_name='filterfield',
            name='field_type_ru',
        ),
        migrations.AlterField(
            model_name='category',
            name='breadcrumb_image',
            field=beercity.utils.CustomLogoField(blank=True, null=True, upload_to='cat-bg-image/', verbose_name='Բաժնի բանների նկար'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=beercity.utils.CustomLogoField(blank=True, null=True, upload_to='cat-catalog-image/', verbose_name='Ընդհանուր կատալոգում երևացող նկար'),
        ),
        migrations.AlterField(
            model_name='category',
            name='logo',
            field=beercity.utils.CustomLogoField(blank=True, null=True, upload_to='cat-img/', verbose_name='Header -ի բաժնի Icon'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=beercity.utils.CustomLogoField(upload_to='product-img/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=beercity.utils.CustomLogoField(upload_to='', verbose_name='product-img/'),
        ),
    ]
