# Generated by Django 3.1 on 2022-03-02 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_auto_20220302_1850'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'Ինգրեդիենտ', 'verbose_name_plural': 'Ինգրեդիենտներ'},
        ),
        migrations.AddField(
            model_name='ingredient',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Ապրանքի անվանում'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='name_hy',
            field=models.CharField(max_length=255, null=True, verbose_name='Ապրանքի անվանում'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Ապրանքի անվանում'),
        ),
    ]
