# Generated by Django 3.1 on 2022-03-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0038_auto_20220303_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='buy_with_this_item',
            field=models.ManyToManyField(blank=True, related_name='buywiththis', to='shop.Ingredient', verbose_name='Այս ապրանքի հետ գնում են նաև'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sold_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Վաճառված քանակություն'),
        ),
    ]
