# Generated by Django 3.1 on 2022-03-13 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0040_auto_20220305_1044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['my_order', '-id'], 'verbose_name': 'Ապրանք', 'verbose_name_plural': 'Ապրանքներ'},
        ),
    ]
