# Generated by Django 3.1 on 2022-03-13 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0041_auto_20220313_1530'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-my_order'], 'verbose_name': 'Ապրանք', 'verbose_name_plural': 'Ապրանքներ'},
        ),
    ]
