# Generated by Django 3.1 on 2022-03-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0042_auto_20220313_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ստեղծման օր'),
        ),
        migrations.AlterField(
            model_name='color',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ձևափոխման օր'),
        ),
        migrations.AlterField(
            model_name='productfeature',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ստեղծման օր'),
        ),
        migrations.AlterField(
            model_name='productfeature',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ձևափոխման օր'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ստեղծման օր'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ձևափոխման օր'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ստեղծման օր'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ձևափոխման օր'),
        ),
        migrations.AlterField(
            model_name='ratingproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ստեղծման օր'),
        ),
        migrations.AlterField(
            model_name='ratingproduct',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ձևափոխման օր'),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ստեղծման օր'),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ձևափոխման օր'),
        ),
    ]
