# Generated by Django 3.1 on 2022-03-15 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0043_auto_20220314_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='show_homepage_products',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='homepage_qty',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Գլխավոր էջում ցուցադրվող subcategory / product -ների քանակ'),
        ),
    ]
