# Generated by Django 3.1 on 2022-03-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0044_auto_20220315_0532'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('title_hy', models.CharField(max_length=255, null=True, unique=True)),
                ('title_ru', models.CharField(max_length=255, null=True, unique=True)),
                ('title_en', models.CharField(max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='productingredient',
            name='infinite',
            field=models.BooleanField(default=False, verbose_name='Անսահմանափակ քանակություն'),
        ),
    ]
