# Generated by Django 3.1 on 2022-03-15 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0046_productingredient_measure_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productingredient',
            name='measure_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.unitmeasurement', verbose_name='Չափման միավոր'),
        ),
    ]
