# Generated by Django 3.1 on 2022-03-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0047_auto_20220315_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productingredient',
            name='infinite',
            field=models.BooleanField(default=False, verbose_name='Անսահմանափակ'),
        ),
    ]
