# Generated by Django 3.1 on 2022-03-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0048_auto_20220316_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productingredient',
            name='qty',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
