# Generated by Django 3.1 on 2022-03-18 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0051_auto_20220318_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitmeasurement',
            name='title_en',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='unitmeasurement',
            name='title_hy',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='unitmeasurement',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
