# Generated by Django 3.1 on 2022-03-18 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0052_auto_20220318_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfeature',
            name='measure_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.unitmeasurement', verbose_name='Չափման միավոր'),
        ),
    ]
