# Generated by Django 3.1 on 2022-03-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0053_productfeature_measure_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
