# Generated by Django 3.1 on 2022-04-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0054_auto_20220318_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='show_minus_and_plus',
            field=models.BooleanField(default=True, verbose_name='Ցուցադրել «+» և «-» նշանները ապրանքի բլոկում'),
        ),
    ]
