# Generated by Django 3.1 on 2023-02-22 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0056_sliderphoneimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sliderphoneimage',
            options={'verbose_name': 'Գլխավոր էջի սլայդերի ֆոնային նկար', 'verbose_name_plural': 'Գլխավոր էջի սլայդերի ֆոնային նկար'},
        ),
    ]
