# Generated by Django 3.1 on 2023-02-22 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0057_auto_20230222_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='short_description_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='short_description_hy',
        ),
        migrations.RemoveField(
            model_name='product',
            name='short_description_ru',
        ),
    ]
