# Generated by Django 3.1 on 2023-02-22 19:37

import beercity.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0058_auto_20230222_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='homepage_name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='homepage_name_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='homepage_name_hy',
        ),
        migrations.RemoveField(
            model_name='category',
            name='homepage_name_ru',
        ),
        migrations.RemoveField(
            model_name='category',
            name='homepage_qty',
        ),
        migrations.RemoveField(
            model_name='category',
            name='notification_text',
        ),
        migrations.RemoveField(
            model_name='category',
            name='notification_text_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='notification_text_hy',
        ),
        migrations.RemoveField(
            model_name='category',
            name='notification_text_ru',
        ),
        migrations.RemoveField(
            model_name='category',
            name='show_bottom',
        ),
        migrations.RemoveField(
            model_name='category',
            name='show_homepage',
        ),
        migrations.RemoveField(
            model_name='category',
            name='show_homepage_products',
        ),
        migrations.RemoveField(
            model_name='category',
            name='sub_title_color',
        ),
        migrations.RemoveField(
            model_name='category',
            name='working_hours_from',
        ),
        migrations.RemoveField(
            model_name='category',
            name='working_hours_to',
        ),
        migrations.AlterField(
            model_name='category',
            name='logo',
            field=beercity.utils.CustomLogoField(blank=True, null=True, upload_to='cat-img/', verbose_name='Գլխավոր էջի կատեգորիայի նկար'),
        ),
        migrations.AlterField(
            model_name='category',
            name='show_in_header',
            field=models.BooleanField(default=False, verbose_name='Ցուցադրել գլխավոր էջում'),
        ),
    ]
