# Generated by Django 3.1 on 2023-02-22 19:39

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0059_auto_20230222_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagebanners',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Տեքստ'),
        ),
        migrations.AddField(
            model_name='homepagebanners',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Տեքստ'),
        ),
        migrations.AddField(
            model_name='homepagebanners',
            name='description_hy',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Տեքստ'),
        ),
        migrations.AddField(
            model_name='homepagebanners',
            name='description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Տեքստ'),
        ),
    ]
