# Generated by Django 3.1 on 2023-02-22 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0060_auto_20230222_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_custom_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Ապրանքի ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Ապրանքի կոդ'),
        ),
    ]
