# Generated by Django 3.1 on 2023-02-22 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0061_auto_20230223_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_qty',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Թույլատրելի մաքսիմալ քանակություն'),
        ),
    ]
