# Generated by Django 3.1 on 2023-02-23 15:51

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0062_product_max_qty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Անուն')),
                ('name_hy', models.CharField(max_length=120, null=True, unique=True, verbose_name='Անուն')),
                ('name_ru', models.CharField(max_length=120, null=True, unique=True, verbose_name='Անուն')),
                ('name_en', models.CharField(max_length=120, null=True, unique=True, verbose_name='Անուն')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Հղում')),
                ('icon', models.FileField(blank=True, null=True, upload_to='', verbose_name='Լոգո')),
                ('shipper_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Էլ. փոստ')),
            ],
            options={
                'verbose_name': 'Բրենդ',
                'verbose_name_plural': 'Բրենդներ',
            },
        ),
        migrations.AddField(
            model_name='homepagebanners',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=18, null=True, samples=None, verbose_name='Գույն'),
        ),
    ]
