# Generated by Django 3.1 on 2023-02-25 12:58

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0064_product_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='add_to_ingredients',
        ),
        migrations.RemoveField(
            model_name='category',
            name='show_category_all_items',
        ),
        migrations.AlterField(
            model_name='category',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='#FF0000', help_text='Ընտրված գույնը երևում է գլխավոր էջում, որպես տվյալ բաժնի ֆոնի գույն', image_field=None, max_length=18, null=True, samples=None, verbose_name='Background -ի գույն'),
        ),
    ]
