# Generated by Django 3.1 on 2023-02-25 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0066_auto_20230225_1703'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productingredient',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='productingredient',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='productingredient',
            name='measure_unit',
        ),
        migrations.RemoveField(
            model_name='productingredient',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='bonus_day_not_working',
        ),
        migrations.RemoveField(
            model_name='product',
            name='mark_as_bestseller_count',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='ProductIngredient',
        ),
    ]
