# Generated by Django 3.1 on 2023-02-25 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0067_auto_20230225_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='show_products',
            field=models.BooleanField(default=True, verbose_name='Ցուցադչել կայքում'),
        ),
    ]
