# Generated by Django 3.1 on 2023-02-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0068_product_show_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='show_products',
            field=models.BooleanField(default=True, verbose_name='Ցուցադրել կայքում'),
        ),
    ]
