# Generated by Django 3.1 on 2023-02-25 15:30

import beercity.utils
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0069_auto_20230225_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='xl_image',
        ),
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True, unique=True, verbose_name='Հղում'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='lg_image',
            field=beercity.utils.CustomLogoField(upload_to='', verbose_name='Նկար'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Տեքստ'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='text_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Տեքստ'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='text_hy',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Տեքստ'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='text_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Տեքստ'),
        ),
    ]
