# Generated by Django 3.1 on 2022-02-20 11:58

import canapea.utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bottomheader',
            name='icon',
        ),
        migrations.AlterField(
            model_name='topheader',
            name='icon',
            field=canapea.utils.CustomLogoField(upload_to=''),
        ),
    ]
