# Generated by Django 3.1 on 2022-02-28 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0004_auto_20220226_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottomheader',
            name='title_en',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Դաշտի անուն'),
        ),
        migrations.AddField(
            model_name='bottomheader',
            name='title_hy',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Դաշտի անուն'),
        ),
        migrations.AddField(
            model_name='bottomheader',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Դաշտի անուն'),
        ),
        migrations.AddField(
            model_name='bottomheader',
            name='url_en',
            field=models.URLField(null=True, verbose_name='Հղում'),
        ),
        migrations.AddField(
            model_name='bottomheader',
            name='url_hy',
            field=models.URLField(null=True, verbose_name='Հղում'),
        ),
        migrations.AddField(
            model_name='bottomheader',
            name='url_ru',
            field=models.URLField(null=True, verbose_name='Հղում'),
        ),
        migrations.AddField(
            model_name='topheader',
            name='title_en',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Դաշտի անուն'),
        ),
        migrations.AddField(
            model_name='topheader',
            name='title_hy',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Դաշտի անուն'),
        ),
        migrations.AddField(
            model_name='topheader',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Դաշտի անուն'),
        ),
        migrations.AddField(
            model_name='topheader',
            name='url_en',
            field=models.URLField(null=True, verbose_name='Հղում'),
        ),
        migrations.AddField(
            model_name='topheader',
            name='url_hy',
            field=models.URLField(null=True, verbose_name='Հղում'),
        ),
        migrations.AddField(
            model_name='topheader',
            name='url_ru',
            field=models.URLField(null=True, verbose_name='Հղում'),
        ),
    ]
