# Generated by Django 3.1 on 2023-02-22 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0005_auto_20220228_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottomheader',
            name='url',
            field=models.CharField(max_length=255, verbose_name='Հղում'),
        ),
        migrations.AlterField(
            model_name='bottomheader',
            name='url_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Հղում'),
        ),
        migrations.AlterField(
            model_name='bottomheader',
            name='url_hy',
            field=models.CharField(max_length=255, null=True, verbose_name='Հղում'),
        ),
        migrations.AlterField(
            model_name='bottomheader',
            name='url_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Հղում'),
        ),
        migrations.AlterField(
            model_name='topheader',
            name='url',
            field=models.CharField(max_length=255, verbose_name='Հղում'),
        ),
        migrations.AlterField(
            model_name='topheader',
            name='url_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Հղում'),
        ),
        migrations.AlterField(
            model_name='topheader',
            name='url_hy',
            field=models.CharField(max_length=255, null=True, verbose_name='Հղում'),
        ),
        migrations.AlterField(
            model_name='topheader',
            name='url_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Հղում'),
        ),
    ]
