# Generated by Django 3.1 on 2022-03-18 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flatpages',
            options={'verbose_name': 'Ստատիկ էջ', 'verbose_name_plural': 'Ստատիկ էջեր'},
        ),
    ]
