# Generated by Django 3.1 on 2022-03-27 09:23

import beercity.utils
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0003_auto_20220318_0839'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=160)),
                ('meta_description', models.TextField(blank=True, max_length=300)),
                ('name', models.CharField(max_length=255, verbose_name='Բաժնի անուն')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Հղում')),
                ('breadcrumb_image', beercity.utils.CustomLogoField(blank=True, null=True, upload_to='blog-cat-bg-image/', verbose_name='Բաժնի բանների նկար')),
                ('breadcrumb_text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Բանների տեքստ')),
                ('my_order', models.PositiveIntegerField(default=0, verbose_name='Դասավորել')),
            ],
            options={
                'verbose_name': 'Բլոգի բաժին',
                'verbose_name_plural': 'Բլոգի բաժիններ',
                'ordering': ['my_order'],
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=160)),
                ('meta_description', models.TextField(blank=True, max_length=300)),
                ('name', models.CharField(max_length=255, verbose_name='Վերնագիր')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Հղում')),
                ('short_text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Հակիրճ տեքստ')),
                ('large_text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Ամբողջական տեքստ')),
                ('views_count', models.PositiveIntegerField(default=0, editable=False)),
                ('image', beercity.utils.CustomLogoField(blank=True, null=True, upload_to='blog-image/', verbose_name='Գլխավոր նկար')),
                ('my_order', models.PositiveIntegerField(default=0, verbose_name='Դասավորել')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flatpages.blogcategory', verbose_name='Ընտրել բաժինը')),
            ],
            options={
                'verbose_name': 'Բլոգ',
                'verbose_name_plural': 'Բլոգ',
                'ordering': ['my_order'],
            },
        ),
    ]
