# Generated by Django 3.1 on 2022-03-27 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0004_blog_blogcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-my_order'], 'verbose_name': 'Բլոգ', 'verbose_name_plural': 'Բլոգ'},
        ),
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'ordering': ['-my_order'], 'verbose_name': 'Բլոգի բաժին', 'verbose_name_plural': 'Բլոգի բաժիններ'},
        ),
    ]
