# Generated by Django 3.1 on 2022-03-27 10:38

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0005_auto_20220327_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='large_text_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Ամբողջական տեքստ'),
        ),
        migrations.AddField(
            model_name='blog',
            name='large_text_hy',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Ամբողջական տեքստ'),
        ),
        migrations.AddField(
            model_name='blog',
            name='large_text_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Ամբողջական տեքստ'),
        ),
        migrations.AddField(
            model_name='blog',
            name='meta_description_en',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='meta_description_hy',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='meta_description_ru',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='meta_title_en',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='meta_title_hy',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='meta_title_ru',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Վերնագիր'),
        ),
        migrations.AddField(
            model_name='blog',
            name='name_hy',
            field=models.CharField(max_length=255, null=True, verbose_name='Վերնագիր'),
        ),
        migrations.AddField(
            model_name='blog',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Վերնագիր'),
        ),
        migrations.AddField(
            model_name='blog',
            name='short_text_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Հակիրճ տեքստ'),
        ),
        migrations.AddField(
            model_name='blog',
            name='short_text_hy',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Հակիրճ տեքստ'),
        ),
        migrations.AddField(
            model_name='blog',
            name='short_text_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Հակիրճ տեքստ'),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='breadcrumb_text_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Բանների տեքստ'),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='breadcrumb_text_hy',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Բանների տեքստ'),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='breadcrumb_text_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Բանների տեքստ'),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='meta_description_en',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='meta_description_hy',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='meta_description_ru',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='meta_title_en',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='meta_title_hy',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='meta_title_ru',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Բաժնի անուն'),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='name_hy',
            field=models.CharField(max_length=255, null=True, verbose_name='Բաժնի անուն'),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Բաժնի անուն'),
        ),
        migrations.CreateModel(
            name='BlogLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=255)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flatpages.blog')),
            ],
        ),
    ]
