# Generated by Django 3.1 on 2022-03-27 10:46

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0006_auto_20220327_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategory',
            name='breadcrumb_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Բանների տեքստ'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='breadcrumb_text_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Բանների տեքստ'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='breadcrumb_text_hy',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Բանների տեքստ'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='breadcrumb_text_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Բանների տեքստ'),
        ),
    ]
