# Generated by Django 3.1 on 2022-03-27 10:47

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0007_auto_20220327_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='short_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Հակիրճ տեքստ'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='short_text_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Հակիրճ տեքստ'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='short_text_hy',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Հակիրճ տեքստ'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='short_text_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Հակիրճ տեքստ'),
        ),
    ]
