# Generated by Django 3.1 on 2022-03-27 12:26

import beercity.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0008_auto_20220327_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=160)),
                ('meta_description', models.TextField(blank=True, max_length=300)),
                ('name', models.CharField(max_length=255, verbose_name='Վերնագիր')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Հղում')),
                ('my_order', models.PositiveIntegerField(default=0, verbose_name='Դասավորել')),
            ],
            options={
                'verbose_name': 'Տեսադարանի բաժին',
                'verbose_name_plural': 'Տեսադարանի բաժիններ',
                'ordering': ['-my_order'],
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=160)),
                ('meta_description', models.TextField(blank=True, max_length=300)),
                ('image', beercity.utils.CustomLogoField(upload_to='')),
                ('my_order', models.PositiveIntegerField(default=0, verbose_name='Դասավորել')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flatpages.gallerycategory', verbose_name='Ընտրել բաժինը')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
