# Generated by Django 3.1 on 2022-03-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0009_gallery_gallerycategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='meta_title',
        ),
        migrations.AlterField(
            model_name='gallery',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ստեղծման օր'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ձևափոխման օր'),
        ),
    ]
