# Generated by Django 3.1 on 2022-03-27 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0010_auto_20220327_1226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['-my_order'], 'verbose_name': 'Նկար', 'verbose_name_plural': 'Տեսադարան'},
        ),
    ]
