# Generated by Django 3.1 on 2022-03-27 12:35

import canapea.utils
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0011_auto_20220327_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerycategory',
            name='breadcrumb_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1, verbose_name='Բանների տեքստ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gallerycategory',
            name='breadcrumbs_image',
            field=canapea.utils.CustomLogoField(default=1, upload_to='gallery-category-bg/', verbose_name='Բաժնի բանների նկար'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gallerycategory',
            name='meta_description_en',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='gallerycategory',
            name='meta_description_hy',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='gallerycategory',
            name='meta_description_ru',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='gallerycategory',
            name='meta_title_en',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='gallerycategory',
            name='meta_title_hy',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='gallerycategory',
            name='meta_title_ru',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='gallerycategory',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Վերնագիր'),
        ),
        migrations.AddField(
            model_name='gallerycategory',
            name='name_hy',
            field=models.CharField(max_length=255, null=True, verbose_name='Վերնագիր'),
        ),
        migrations.AddField(
            model_name='gallerycategory',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Վերնագիր'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=canapea.utils.CustomLogoField(upload_to='gallery/'),
        ),
    ]
