# Generated by Django 3.1 on 2022-03-27 12:36

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0012_auto_20220327_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerycategory',
            name='breadcrumb_text_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Բանների տեքստ'),
        ),
        migrations.AddField(
            model_name='gallerycategory',
            name='breadcrumb_text_hy',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Բանների տեքստ'),
        ),
        migrations.AddField(
            model_name='gallerycategory',
            name='breadcrumb_text_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Բանների տեքստ'),
        ),
    ]
