# Generated by Django 3.1 on 2022-03-27 12:39

import beercity.utils
import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0013_auto_20220327_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerycategory',
            name='breadcrumb_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Բանների տեքստ'),
        ),
        migrations.AlterField(
            model_name='gallerycategory',
            name='breadcrumb_text_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Բանների տեքստ'),
        ),
        migrations.AlterField(
            model_name='gallerycategory',
            name='breadcrumb_text_hy',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Բանների տեքստ'),
        ),
        migrations.AlterField(
            model_name='gallerycategory',
            name='breadcrumb_text_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Բանների տեքստ'),
        ),
        migrations.AlterField(
            model_name='gallerycategory',
            name='breadcrumbs_image',
            field=beercity.utils.CustomLogoField(blank=True, null=True, upload_to='gallery-category-bg/', verbose_name='Բաժնի բանների նկար'),
        ),
    ]
