# Generated by Django 3.1 on 2022-03-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0014_auto_20220327_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerycategory',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Բաժնի անուն'),
        ),
        migrations.AlterField(
            model_name='gallerycategory',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Բաժնի անուն'),
        ),
        migrations.AlterField(
            model_name='gallerycategory',
            name='name_hy',
            field=models.CharField(max_length=255, null=True, verbose_name='Բաժնի անուն'),
        ),
        migrations.AlterField(
            model_name='gallerycategory',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Բաժնի անուն'),
        ),
    ]
