# Generated by Django 3.1 on 2022-03-31 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0015_auto_20220327_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ստեղծման օր')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ձևափոխման օր')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('question', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
