# Generated by Django 3.1 on 2022-03-31 18:21

import beercity.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0016_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsIcons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', beercity.utils.CustomLogoField(upload_to='')),
                ('url', models.CharField(max_length=1000, verbose_name='Հղում')),
                ('text', models.CharField(max_length=255, verbose_name='')),
            ],
            options={
                'verbose_name': '«Հետադարձ կապ» էջի icon',
                'verbose_name_plural': '«Հետադարձ կապ» էջի icon-ներ',
            },
        ),
        migrations.CreateModel(
            name='ContactUsThemes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ստեղծման օր')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ձևափոխման օր')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Թեմայի անուն')),
            ],
            options={
                'verbose_name': 'Հետադարձ կապի թեմա',
                'verbose_name_plural': 'Հետադարձ կապի թեմաներ',
            },
        ),
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'Հետադարձ կապ', 'verbose_name_plural': 'Հետադարձ կապ'},
        ),
    ]
