# Generated by Django 3.1 on 2022-03-31 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0017_auto_20220331_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactusicons',
            name='my_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Դասավորել'),
        ),
        migrations.AlterField(
            model_name='contactusicons',
            name='text',
            field=models.CharField(max_length=255, verbose_name='Տեքստ'),
        ),
    ]
