# Generated by Django 3.1 on 2022-03-31 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0018_auto_20220331_1837'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactusicons',
            options={'ordering': ['-my_order'], 'verbose_name': '«Հետադարձ կապ» էջի icon', 'verbose_name_plural': '«Հետադարձ կապ» էջի icon-ներ'},
        ),
    ]
