# Generated by Django 3.1 on 2022-03-31 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0019_auto_20220331_1837'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactusthemes',
            options={'ordering': ['-my_order'], 'verbose_name': 'Հետադարձ կապի թեմա', 'verbose_name_plural': 'Հետադարձ կապի թեմաներ'},
        ),
        migrations.AddField(
            model_name='contactusthemes',
            name='my_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Դասավորել'),
        ),
        migrations.AddField(
            model_name='contactusthemes',
            name='name_en',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Թեմայի անուն'),
        ),
        migrations.AddField(
            model_name='contactusthemes',
            name='name_hy',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Թեմայի անուն'),
        ),
        migrations.AddField(
            model_name='contactusthemes',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Թեմայի անուն'),
        ),
    ]
