# Generated by Django 3.1 on 2022-03-31 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0020_auto_20220331_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='theme',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
