# Generated by Django 3.1 on 2022-03-31 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0021_contactus_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='theme',
        ),
    ]
