# Generated by Django 3.1 on 2022-03-31 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0022_remove_contactus_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ստեղծման օր')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ձևափոխման օր')),
                ('question', models.TextField()),
                ('question_hy', models.TextField(null=True)),
                ('question_ru', models.TextField(null=True)),
                ('question_en', models.TextField(null=True)),
                ('answer', models.TextField()),
                ('answer_hy', models.TextField(null=True)),
                ('answer_ru', models.TextField(null=True)),
                ('answer_en', models.TextField(null=True)),
                ('my_order', models.PositiveIntegerField(default=0, verbose_name='Դասավորել')),
            ],
            options={
                'verbose_name': 'Հաճախակի տրվող հարց',
                'verbose_name_plural': 'Հաճախակի տրվող հարցեր',
                'ordering': ['-my_order'],
            },
        ),
    ]
