# Generated by Django 3.1 on 2022-04-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0023_faqmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqmodel',
            name='answer',
            field=models.TextField(max_length=500, verbose_name='Պատասխան'),
        ),
        migrations.AlterField(
            model_name='faqmodel',
            name='answer_en',
            field=models.TextField(max_length=500, null=True, verbose_name='Պատասխան'),
        ),
        migrations.AlterField(
            model_name='faqmodel',
            name='answer_hy',
            field=models.TextField(max_length=500, null=True, verbose_name='Պատասխան'),
        ),
        migrations.AlterField(
            model_name='faqmodel',
            name='answer_ru',
            field=models.TextField(max_length=500, null=True, verbose_name='Պատասխան'),
        ),
        migrations.AlterField(
            model_name='faqmodel',
            name='question',
            field=models.CharField(max_length=500, verbose_name='Հարց'),
        ),
        migrations.AlterField(
            model_name='faqmodel',
            name='question_en',
            field=models.CharField(max_length=500, null=True, verbose_name='Հարց'),
        ),
        migrations.AlterField(
            model_name='faqmodel',
            name='question_hy',
            field=models.CharField(max_length=500, null=True, verbose_name='Հարց'),
        ),
        migrations.AlterField(
            model_name='faqmodel',
            name='question_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='Հարց'),
        ),
    ]
