# Generated by Django 3.1 on 2023-02-23 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0025_auto_20220401_0914'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUsThemes',
        ),
    ]
