# Generated by Django 3.1 on 2023-02-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0026_delete_contactusthemes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsPageIframe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iframe', models.TextField()),
            ],
        ),
    ]
