# Generated by Django 3.1 on 2023-02-23 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0027_contactuspageiframe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactuspageiframe',
            options={'verbose_name': 'IFrame', 'verbose_name_plural': 'IFrame'},
        ),
    ]
