# Generated by Django 3.1 on 2023-02-24 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0028_auto_20230223_2010'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
        migrations.DeleteModel(
            name='ContactUsIcons',
        ),
        migrations.DeleteModel(
            name='ContactUsPageIframe',
        ),
    ]
