# Generated by Django 3.1 on 2023-02-25 15:30

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0029_auto_20230224_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatpages',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Տեքստ'),
        ),
        migrations.AlterField(
            model_name='flatpages',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Տեքստ'),
        ),
        migrations.AlterField(
            model_name='flatpages',
            name='content_hy',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Տեքստ'),
        ),
        migrations.AlterField(
            model_name='flatpages',
            name='content_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Տեքստ'),
        ),
        migrations.AlterField(
            model_name='flatpages',
            name='page_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Էջի անուն'),
        ),
        migrations.AlterField(
            model_name='flatpages',
            name='page_name_en',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Էջի անուն'),
        ),
        migrations.AlterField(
            model_name='flatpages',
            name='page_name_hy',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Էջի անուն'),
        ),
        migrations.AlterField(
            model_name='flatpages',
            name='page_name_ru',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Էջի անուն'),
        ),
        migrations.AlterField(
            model_name='flatpages',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Հղում'),
        ),
    ]
