# Generated by Django 3.1 on 2023-03-02 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='features',
            field=models.TextField(blank=True, null=True),
        ),
    ]
