# Generated by Django 3.1 on 2023-03-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20230302_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='features',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
