# Generated by Django 3.1 on 2023-03-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_remove_cartitem_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='features',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
