# Generated by Django 3.1 on 2022-02-19 19:42

import beercity.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0002_auto_20220219_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Անուն')),
                ('icon', beercity.utils.CustomLogoField(blank=True, upload_to='')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Հղում դեպի գործընկերոջ կայքէջ')),
            ],
        ),
    ]
