# Generated by Django 3.1 on 2022-02-19 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0004_auto_20220219_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('my_order', models.PositiveIntegerField(default=0, verbose_name='Դասավորել')),
            ],
            options={
                'verbose_name': 'Footer -ի բաժին',
                'verbose_name_plural': 'Footer -ի բաժիններ',
                'ordering': ['my_order'],
            },
        ),
        migrations.AlterModelOptions(
            name='partners',
            options={'ordering': ['my_order'], 'verbose_name': 'Գործընկեր', 'verbose_name_plural': 'Գործընկերներ'},
        ),
        migrations.AddField(
            model_name='partners',
            name='my_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Դասավորել'),
        ),
        migrations.AddField(
            model_name='personaldata',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Հղում'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Անուն (alt)'),
        ),
    ]
