# Generated by Django 3.1 on 2022-02-19 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0005_auto_20220219_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='footer.footercategory', verbose_name='Բաժնի անուն'),
            preserve_default=False,
        ),
    ]
