# Generated by Django 3.1 on 2022-02-19 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0006_footer_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='is_logged',
            field=models.BooleanField(default=False, help_text='Դաշտը հասանելի է միայն մուտք եղած օգտատերերին'),
        ),
    ]
