# Generated by Django 3.1 on 2022-02-19 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0007_footer_is_logged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='footer.footercategory', verbose_name='Բաժնի անուն'),
        ),
    ]
