# Generated by Django 3.1 on 2022-02-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0009_auto_20220219_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='is_logged',
            field=models.CharField(blank=True, choices=[('logged', 'Օգտատերեր'), ('guests', 'Հյուրեր')], help_text='Դաշտի հասանելիության տիրույթ, դաշտի դատարկ լինելու դեպքում այն տեսանելի կլինի բոլորին', max_length=120, null=True, verbose_name='Ցուցադրման տիրույթ'),
        ),
    ]
