# Generated by Django 3.1 on 2022-02-28 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0012_auto_20220226_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankicons',
            name='title_en',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Անուն (alt)'),
        ),
        migrations.AddField(
            model_name='bankicons',
            name='title_hy',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Անուն (alt)'),
        ),
        migrations.AddField(
            model_name='bankicons',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Անուն (alt)'),
        ),
        migrations.AddField(
            model_name='bankicons',
            name='url_en',
            field=models.URLField(blank=True, null=True, verbose_name='Հղում'),
        ),
        migrations.AddField(
            model_name='bankicons',
            name='url_hy',
            field=models.URLField(blank=True, null=True, verbose_name='Հղում'),
        ),
        migrations.AddField(
            model_name='bankicons',
            name='url_ru',
            field=models.URLField(blank=True, null=True, verbose_name='Հղում'),
        ),
        migrations.AddField(
            model_name='footer',
            name='title_en',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Դաշտի անուն'),
        ),
        migrations.AddField(
            model_name='footer',
            name='title_hy',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Դաշտի անուն'),
        ),
        migrations.AddField(
            model_name='footer',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Դաշտի անուն'),
        ),
        migrations.AddField(
            model_name='footer',
            name='url_en',
            field=models.URLField(null=True, verbose_name='Հղում'),
        ),
        migrations.AddField(
            model_name='footer',
            name='url_hy',
            field=models.URLField(null=True, verbose_name='Հղում'),
        ),
        migrations.AddField(
            model_name='footer',
            name='url_ru',
            field=models.URLField(null=True, verbose_name='Հղում'),
        ),
        migrations.AddField(
            model_name='footercategory',
            name='title_en',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='footercategory',
            name='title_hy',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='footercategory',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='partners',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Անուն (alt)'),
        ),
        migrations.AddField(
            model_name='partners',
            name='name_hy',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Անուն (alt)'),
        ),
        migrations.AddField(
            model_name='partners',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Անուն (alt)'),
        ),
        migrations.AddField(
            model_name='partners',
            name='url_en',
            field=models.URLField(blank=True, null=True, verbose_name='Հղում դեպի գործընկերոջ կայքէջ'),
        ),
        migrations.AddField(
            model_name='partners',
            name='url_hy',
            field=models.URLField(blank=True, null=True, verbose_name='Հղում դեպի գործընկերոջ կայքէջ'),
        ),
        migrations.AddField(
            model_name='partners',
            name='url_ru',
            field=models.URLField(blank=True, null=True, verbose_name='Հղում դեպի գործընկերոջ կայքէջ'),
        ),
        migrations.AddField(
            model_name='personaldata',
            name='text_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Տեքստ'),
        ),
        migrations.AddField(
            model_name='personaldata',
            name='text_hy',
            field=models.CharField(max_length=255, null=True, verbose_name='Տեքստ'),
        ),
        migrations.AddField(
            model_name='personaldata',
            name='text_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Տեքստ'),
        ),
        migrations.AddField(
            model_name='personaldata',
            name='url_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Հղում'),
        ),
        migrations.AddField(
            model_name='personaldata',
            name='url_hy',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Հղում'),
        ),
        migrations.AddField(
            model_name='personaldata',
            name='url_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Հղում'),
        ),
        migrations.AddField(
            model_name='socialicons',
            name='title_en',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Անուն (alt)'),
        ),
        migrations.AddField(
            model_name='socialicons',
            name='title_hy',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Անուն (alt)'),
        ),
        migrations.AddField(
            model_name='socialicons',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Անուն (alt)'),
        ),
        migrations.AddField(
            model_name='socialicons',
            name='url_en',
            field=models.URLField(null=True, verbose_name='Հղում'),
        ),
        migrations.AddField(
            model_name='socialicons',
            name='url_hy',
            field=models.URLField(null=True, verbose_name='Հղում'),
        ),
        migrations.AddField(
            model_name='socialicons',
            name='url_ru',
            field=models.URLField(null=True, verbose_name='Հղում'),
        ),
    ]
