# Generated by Django 3.1 on 2022-02-28 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0013_auto_20220228_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partners',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Անուն (alt)'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='name_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Անուն (alt)'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='name_hy',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Անուն (alt)'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='name_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Անուն (alt)'),
        ),
    ]
