# Generated by Django 3.1 on 2023-02-22 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0014_auto_20220228_2223'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Partners',
        ),
    ]
