# Generated by Django 3.1 on 2023-02-27 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0015_delete_partners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footercategory',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Անուն'),
        ),
        migrations.AlterField(
            model_name='footercategory',
            name='title_en',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Անուն'),
        ),
        migrations.AlterField(
            model_name='footercategory',
            name='title_hy',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Անուն'),
        ),
        migrations.AlterField(
            model_name='footercategory',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Անուն'),
        ),
    ]
