# Generated by Django 3.1 on 2022-03-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BreadcrumbTexts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(choices=[('catalog', 'Տեսականի'), ('sale', 'Ակցիա'), ('new', 'Նորույթ'), ('best_seller', 'Հատուկ առաջարկ')], max_length=150, unique=True)),
                ('breadcrumbs_text', models.TextField(blank=True, null=True)),
                ('breadcrumbs_image', models.FileField(blank=True, null=True, upload_to='breadcrumb_images/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
