# Generated by Django 3.1 on 2022-03-04 18:41

import beercity.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breadcrumbs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breadcrumbtexts',
            options={'verbose_name': 'Breadcrumb -ի կոնտենտ', 'verbose_name_plural': 'Breadcrumb -ի կոնտենտ'},
        ),
        migrations.AddField(
            model_name='breadcrumbtexts',
            name='page_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='breadcrumbtexts',
            name='breadcrumbs_image',
            field=beercity.utils.CustomLogoField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='breadcrumbtexts',
            name='breadcrumbs_text',
            field=models.TextField(blank=True, null=True, verbose_name='Breadcrumb -ի տեքստ'),
        ),
        migrations.AlterField(
            model_name='breadcrumbtexts',
            name='location',
            field=models.CharField(choices=[('catalog', 'Տեսականի'), ('sale', 'Ակցիա'), ('new', 'Նորույթ'), ('best_seller', 'Հատուկ առաջարկ')], max_length=150, unique=True, verbose_name='Ընտրեք էջը'),
        ),
    ]
