# Generated by Django 3.1 on 2022-03-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breadcrumbs', '0004_auto_20220314_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='breadcrumbtexts',
            name='breadcrumbs_text_en',
            field=models.TextField(blank=True, null=True, verbose_name='Breadcrumb -ի տեքստ'),
        ),
        migrations.AddField(
            model_name='breadcrumbtexts',
            name='breadcrumbs_text_hy',
            field=models.TextField(blank=True, null=True, verbose_name='Breadcrumb -ի տեքստ'),
        ),
        migrations.AddField(
            model_name='breadcrumbtexts',
            name='breadcrumbs_text_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Breadcrumb -ի տեքստ'),
        ),
        migrations.AddField(
            model_name='breadcrumbtexts',
            name='page_title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='breadcrumbtexts',
            name='page_title_hy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='breadcrumbtexts',
            name='page_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
