# Generated by Django 3.1 on 2022-03-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breadcrumbs', '0007_auto_20220327_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breadcrumbtexts',
            name='location',
            field=models.CharField(choices=[('catalog', 'Տեսականի'), ('sale', 'Ակցիա'), ('new', 'Նորույթ'), ('best_seller', 'Բեսթսելլեր'), ('special_offer', 'Հատուկ առաջարկ'), ('search', 'Որոնում'), ('blog', 'Բլոգ'), ('gallery', 'Տեսադարան')], max_length=150, unique=True, verbose_name='Ընտրեք էջը'),
        ),
    ]
