# Generated by Django 3.1 on 2023-03-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('1', 'Կանխիկ տեղում'), ('2', 'Կանխիկ առաքման պահին'), ('3', 'Անկանխիկ (ARCA/ VISA/ MASTERCARD)'), ('4', 'Անկանխիկ ("Idram")')], default=1, max_length=30),
            preserve_default=False,
        ),
    ]
