# Generated by Django 3.1 on 2023-03-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20230304_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='from_price',
            field=models.FloatField(verbose_name='Գումարային մինիմալ շեմ'),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='percent',
            field=models.FloatField(blank=True, null=True, verbose_name='Զեղչ -ի չափը'),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='sale_type',
            field=models.CharField(choices=[('1', '%'), ('2', 'Դրամ')], max_length=30, verbose_name='Զեղչ -ի ձևը'),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='to_price',
            field=models.FloatField(verbose_name='Գումարային մաքսիմալ շեմ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Հասցե'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cart_total_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Ապրանքների գումարային արժեք'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Առաքման գումար'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('1', 'Առաքում'), ('2', 'Կվերցնեմ ինքս')], max_length=30, verbose_name='Առաքման ձև'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Էլ. հասցե'),
        ),
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Անուն'),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Ազգանուն'),
        ),
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Նշումներ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_total_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Պատվերի աբողջական արժեք'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('1', 'Կանխիկ տեղում'), ('2', 'Կանխիկ առաքման պահին'), ('3', 'Անկանխիկ (ARCA/ VISA/ MASTERCARD)'), ('4', 'Անկանխիկ ("Idram")')], max_length=30, verbose_name='Վճարման եղանակ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(max_length=30, verbose_name='Հեռ.'),
        ),
        migrations.AlterField(
            model_name='order',
            name='region',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Բնակավայր'),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Մարզ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Փոխանցման ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Փոխանցման կարգավիճակ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='used_bonuses_count',
            field=models.FloatField(blank=True, null=True, verbose_name='Օգտագործված բոնուսների քանակ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='used_promo_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Օգտագործված promo կոդ'),
        ),
        migrations.AlterField(
            model_name='promocodes',
            name='from_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Գործում է սկսած'),
        ),
        migrations.AlterField(
            model_name='promocodes',
            name='max_usability',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Մաքսիմում կարելի է օգտագործել'),
        ),
        migrations.AlterField(
            model_name='promocodes',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Կոդ'),
        ),
        migrations.AlterField(
            model_name='promocodes',
            name='percent',
            field=models.FloatField(blank=True, null=True, verbose_name='Զեղչ -ի չափը'),
        ),
        migrations.AlterField(
            model_name='promocodes',
            name='sale_type',
            field=models.CharField(choices=[('1', '%'), ('2', 'Դրամ')], max_length=30, verbose_name='Զեղչ -ի ձևը'),
        ),
        migrations.AlterField(
            model_name='promocodes',
            name='to_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Գործում է մինչև'),
        ),
    ]
