# Generated by Django 3.1 on 2023-03-04 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20230304_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='percent',
            field=models.FloatField(default=100, verbose_name='Զեղչ -ի չափը'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='promocodes',
            name='percent',
            field=models.FloatField(default=100, verbose_name='Զեղչ -ի չափը'),
            preserve_default=False,
        ),
    ]
