# Generated by Django 3.1 on 2023-03-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20230304_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_delivery_status',
            field=models.IntegerField(choices=[(1, 'Ընթացքի մեջ'), (2, 'Ճանապարհին'), (3, 'Առաքված'), (4, 'Պատրաստ է վերցնելու')], default=1, verbose_name='Առաքման կարգավիճակ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='order_payment_status',
            field=models.IntegerField(choices=[(1, 'Սպասման մեջ'), (2, 'Վճարված'), (3, 'Չվճարված'), (4, 'Վերադարձված')], default=1, verbose_name='Վճարման կարգավիճակ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Բանկային փոխանցման ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Բանկային փոխանցման կարգավիճակ'),
        ),
    ]
