# Generated by Django 3.1 on 2023-03-05 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20230304_2350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_type',
            new_name='delivery',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='payment_type',
            new_name='payments',
        ),
    ]
