# Generated by Django 3.1 on 2023-03-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20230305_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_delivery_status',
            field=models.IntegerField(blank=True, choices=[(1, 'Ընթացքի մեջ'), (2, 'Ճանապարհին'), (3, 'Առաքված'), (4, 'Պատրաստ է վերցնելու')], null=True, verbose_name='Առաքման կարգավիճակ'),
        ),
    ]
