# Generated by Django 3.1 on 2023-03-05 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0071_category_social_image'),
        ('orders', '0009_auto_20230305_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250, verbose_name='Ապրանքի անուն')),
                ('product_image', models.ImageField(upload_to='', verbose_name='Նկար')),
                ('product_price', models.FloatField(default=0.0, verbose_name='Գին')),
                ('quantity', models.IntegerField(default=0, verbose_name='Քանակ')),
                ('item_total_price', models.FloatField(default=0, verbose_name='Գումար')),
                ('description', models.CharField(blank=True, max_length=300, null=True, verbose_name='Նկարագրություն')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product')),
            ],
        ),
    ]
