# Generated by Django 3.1 on 2023-03-11 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20230309_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sale_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Պատվերից զեղչվել է'),
        ),
    ]
