# Generated by Django 3.1 on 2023-03-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_sale_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationConstants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus_to_amd', models.FloatField(default=1, verbose_name='1 բոնուսային միավորը AMD -ի տեսքով')),
                ('promo_percent_type', models.CharField(choices=[('1', '%'), ('2', 'Դրամ')], max_length=120, verbose_name='Տիպը')),
                ('promo_sale', models.FloatField(default=1, verbose_name='Տրամադրվող զեղչի չափ')),
            ],
        ),
        migrations.AlterField(
            model_name='bonus',
            name='sale_type',
            field=models.CharField(choices=[('1', '%'), ('2', 'Դրամ')], max_length=30, verbose_name='Տիպը'),
        ),
        migrations.AlterField(
            model_name='promocodes',
            name='sale_type',
            field=models.CharField(choices=[('1', '%'), ('2', 'Դրամ')], max_length=30, verbose_name='Տիպը'),
        ),
    ]
