# Generated by Django 3.1 on 2022-05-15 13:03

import canapea.utils
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Աշխատանքի ժամկետ')),
            ],
            options={
                'verbose_name': 'Աշխատանքի ժամկետ',
                'verbose_name_plural': 'Աշխատանքի ժամկետներ',
            },
        ),
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=160)),
                ('meta_description', models.TextField(blank=True, max_length=300)),
                ('name', models.CharField(max_length=255, verbose_name='Անուն')),
                ('icon', canapea.utils.CustomLogoField(blank=True, null=True, upload_to='', verbose_name='Նկար')),
                ('slug', models.SlugField(blank=True, max_length=2000, null=True, verbose_name='Հղում')),
                ('breadcrumbs_text', models.TextField(blank=True, null=True, verbose_name='Breadcrumb -ի տեքստ')),
                ('breadcrumbs_image', canapea.utils.CustomLogoField(blank=True, null=True, upload_to='', verbose_name='Breadcrumb -ի Նկար')),
            ],
            options={
                'verbose_name': 'Աշխատանքի բաժին',
                'verbose_name_plural': 'Աշխատանքի բաժիններ',
            },
        ),
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Աշխատանքի տիպը')),
            ],
            options={
                'verbose_name': 'Աշխատանքի տիպը',
                'verbose_name_plural': 'Աշխատանքի տիպը',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Տեղանուն')),
            ],
            options={
                'verbose_name': 'Տեղանուն',
                'verbose_name_plural': 'Տեղանուն',
            },
        ),
        migrations.CreateModel(
            name='JobItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=160)),
                ('meta_description', models.TextField(blank=True, max_length=300)),
                ('name', models.CharField(max_length=300, verbose_name='Հաստիքի անուն')),
                ('slug', models.SlugField(blank=True, max_length=1000, null=True, verbose_name='Հղում')),
                ('short_description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Հակիրճ Նկարագիր')),
                ('large_description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Ամբողջական Նկարագիր')),
                ('icon', canapea.utils.CustomLogoField(blank=True, null=True, upload_to='')),
                ('dateline', models.DateTimeField(blank=True, null=True, verbose_name='Հասանելի է մինչև')),
                ('salary_from', models.IntegerField(blank=True, null=True, verbose_name='Աշխատավարձը սկսած')),
                ('salary_to', models.IntegerField(blank=True, null=True, verbose_name='Աշխատավարձը մինչև')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.jobcategory', verbose_name='Բաժին')),
                ('job_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.jobtype', verbose_name='Աշխատանքի տիպը')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.location', verbose_name='Տեղանուն')),
            ],
            options={
                'verbose_name': 'Թափուր հաստիք',
                'verbose_name_plural': 'Թափուր հաստիքներ',
            },
        ),
    ]
