# Generated by Django 3.1 on 2022-05-15 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobitem',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.location', verbose_name='Գտնվելու վայրը'),
        ),
    ]
