# Generated by Django 3.1 on 2022-05-15 20:03

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20220515_1329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employmentterm',
            options={'verbose_name': 'Աշխատանքի պայման', 'verbose_name_plural': 'Աշխատանքի պայմաններ'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Գտնվելու վայրը', 'verbose_name_plural': 'Գտնվելու վայրը'},
        ),
        migrations.AddField(
            model_name='employmentterm',
            name='title_en',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Աշխատանքի պայման'),
        ),
        migrations.AddField(
            model_name='employmentterm',
            name='title_hy',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Աշխատանքի պայման'),
        ),
        migrations.AddField(
            model_name='employmentterm',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Աշխատանքի պայման'),
        ),
        migrations.AddField(
            model_name='jobcategory',
            name='breadcrumbs_text_en',
            field=models.TextField(blank=True, null=True, verbose_name='Breadcrumb -ի տեքստ'),
        ),
        migrations.AddField(
            model_name='jobcategory',
            name='breadcrumbs_text_hy',
            field=models.TextField(blank=True, null=True, verbose_name='Breadcrumb -ի տեքստ'),
        ),
        migrations.AddField(
            model_name='jobcategory',
            name='breadcrumbs_text_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Breadcrumb -ի տեքստ'),
        ),
        migrations.AddField(
            model_name='jobcategory',
            name='meta_description_en',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='jobcategory',
            name='meta_description_hy',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='jobcategory',
            name='meta_description_ru',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='jobcategory',
            name='meta_title_en',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='jobcategory',
            name='meta_title_hy',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='jobcategory',
            name='meta_title_ru',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='jobcategory',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Անուն'),
        ),
        migrations.AddField(
            model_name='jobcategory',
            name='name_hy',
            field=models.CharField(max_length=255, null=True, verbose_name='Անուն'),
        ),
        migrations.AddField(
            model_name='jobcategory',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Անուն'),
        ),
        migrations.AddField(
            model_name='jobitem',
            name='employment_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job.employmentterm', verbose_name='Աշխատանքի պայմաններ'),
        ),
        migrations.AddField(
            model_name='jobitem',
            name='large_description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Ամբողջական Նկարագիր'),
        ),
        migrations.AddField(
            model_name='jobitem',
            name='large_description_hy',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Ամբողջական Նկարագիր'),
        ),
        migrations.AddField(
            model_name='jobitem',
            name='large_description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Ամբողջական Նկարագիր'),
        ),
        migrations.AddField(
            model_name='jobitem',
            name='meta_description_en',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='jobitem',
            name='meta_description_hy',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='jobitem',
            name='meta_description_ru',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='jobitem',
            name='meta_title_en',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='jobitem',
            name='meta_title_hy',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='jobitem',
            name='meta_title_ru',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='jobitem',
            name='name_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Հաստիքի անուն'),
        ),
        migrations.AddField(
            model_name='jobitem',
            name='name_hy',
            field=models.CharField(max_length=300, null=True, verbose_name='Հաստիքի անուն'),
        ),
        migrations.AddField(
            model_name='jobitem',
            name='name_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Հաստիքի անուն'),
        ),
        migrations.AddField(
            model_name='jobitem',
            name='short_description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Հակիրճ Նկարագիր'),
        ),
        migrations.AddField(
            model_name='jobitem',
            name='short_description_hy',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Հակիրճ Նկարագիր'),
        ),
        migrations.AddField(
            model_name='jobitem',
            name='short_description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Հակիրճ Նկարագիր'),
        ),
        migrations.AddField(
            model_name='jobtype',
            name='title_en',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Աշխատանքի տիպը'),
        ),
        migrations.AddField(
            model_name='jobtype',
            name='title_hy',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Աշխատանքի տիպը'),
        ),
        migrations.AddField(
            model_name='jobtype',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Աշխատանքի տիպը'),
        ),
        migrations.AddField(
            model_name='location',
            name='title_en',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Տեղանուն'),
        ),
        migrations.AddField(
            model_name='location',
            name='title_hy',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Տեղանուն'),
        ),
        migrations.AddField(
            model_name='location',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Տեղանուն'),
        ),
        migrations.AlterField(
            model_name='employmentterm',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Աշխատանքի պայման'),
        ),
        migrations.AlterField(
            model_name='jobitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job.jobcategory', verbose_name='Բաժին'),
        ),
        migrations.AlterField(
            model_name='jobitem',
            name='job_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job.jobtype', verbose_name='Աշխատանքի տիպը'),
        ),
        migrations.AlterField(
            model_name='jobitem',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job.location', verbose_name='Գտնվելու վայրը'),
        ),
    ]
