# Generated by Django 3.1 on 2022-05-16 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_auto_20220515_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, verbose_name='Հղում'),
        ),
        migrations.AlterField(
            model_name='jobitem',
            name='slug',
            field=models.SlugField(blank=True, max_length=700, null=True, verbose_name='Հղում'),
        ),
    ]
