# Generated by Django 3.1 on 2022-05-17 17:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_auto_20220516_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobitem',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Հաստիքը առկա է'),
        ),
        migrations.CreateModel(
            name='SubmittedResumes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ստեղծման օր')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ձևափոխման օր')),
                ('file', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'pdf'])])),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.jobitem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
