# Generated by Django 3.1 on 2022-05-17 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_auto_20220517_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submittedresumes',
            old_name='file',
            new_name='cv',
        ),
    ]
