# Generated by Django 3.1 on 2022-05-17 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_auto_20220517_1811'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submittedresumes',
            options={'verbose_name': 'Ուղարկված CV -ն', 'verbose_name_plural': 'Ուղարկված CV -ներ'},
        ),
        migrations.AddField(
            model_name='submittedresumes',
            name='job_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='submittedresumes',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='job.jobitem'),
        ),
        migrations.CreateModel(
            name='CustomResumeForJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ստեղծման օր')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ձևափոխման օր')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='job.jobitem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
