# Generated by Django 3.1 on 2022-05-17 20:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_auto_20220517_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='customresumeforjob',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customresumeforjob',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customresumeforjob',
            name='edito6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customresumeforjob',
            name='editor1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customresumeforjob',
            name='editor2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customresumeforjob',
            name='editor3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customresumeforjob',
            name='editor4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customresumeforjob',
            name='editor5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customresumeforjob',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customresumeforjob',
            name='image',
            field=models.FileField(default=1, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'jpg'])]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customresumeforjob',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='customresumeforjob',
            name='phone',
            field=models.ManyToManyField(blank=True, null=True, to='job.PhoneNumbers'),
        ),
    ]
