# Generated by Django 3.1 on 2022-05-17 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_customresumeforjob_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customresumeforjob',
            old_name='image',
            new_name='avatar',
        ),
    ]
